packages:
  - apps/*
  - packages/*
  - docs/*
  - services/*
  - lib/*
ignoredBuiltDependencies:
  - core-js
  - core-js-pure
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - msgpackr-extract
catalog:
  "typescript": "^6.0.2"
  "@types/node": "^25.5.2"
  "tsx": "4.21.0"
  "effect": ^3.19.15
  "@effect/cli": "0.75.0"
  "@effect/language-service": ^0.85.1
  "@effect/opentelemetry": ^0.63.0
  "@effect/platform": ^0.96.0
  "@effect/platform-node": ^0.106.0
  "@effect/sql": ^0.51.0
  "@effect/sql-pg": ^0.52.1
  "@effect/vitest": ^0.29.0
  "vitest": "^4.1.3"
