packages:
  - apps/*
  - packages/*
  - docs/*
  - services/*
  - lib/*
ignoredBuiltDependencies:
  - core-js
  - core-js-pure
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - msgpackr-extract
catalog:
  "typescript": "^5.9.3"
  "@types/node": "^25.1.0"
  "tsx": "4.21.0"
  "effect": ^3.19.15
  "@effect/cli": "0.73.1"
  "@effect/language-service": ^0.72.0
  "@effect/opentelemetry": ^0.61.0
  "@effect/platform": ^0.94.2
  "@effect/platform-node": ^0.104.1
  "@effect/sql": ^0.49.0
  "@effect/sql-pg": ^0.50.1
  "@effect/vitest": ^0.27.0
  "vitest": "^3.2.0"
